name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3.2.0
      with:
        registry: harbor.k8s-homolog.ifrn.edu.br
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v4.1.7
    - name: BuildAndPushImageOnHarbor
      run: |
        echo "Efetuando build da imagem..."
        docker build ./ -t harbor.k8s-homolog.ifrn.edu.br/escritoriodedados/diagnostico-ofertas-if:${{ github.run_number }}

        echo "Fazendo push da imagem no registry Harbor..."
        docker push harbor.k8s-homolog.ifrn.edu.br/escritoriodedados/diagnostico-ofertas-if:${{ github.run_number }}

    # também clona repositório de manifestos
    - name: Clone Manifests Repository
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        ssh-add - <<< "${{secrets.DEPLOY_SSH_PRIVATE_KEY}}"

        echo "Clonando repositório de manifestos..."
        git clone git@github.com:ifrn-oficial/diagnostico-ofertas-if_manifests
        
    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq
    - name: Update YAML File
      run: |
        echo "Listando diretório raiz..."
        ls -lah

        echo "Listando diretório diagnostico-ofertas-if_manifests..."
        ls -lah diagnostico-ofertas-if_manifests

        yq -i '.spec.template.spec.containers[0].image = "harbor.k8s-homolog.ifrn.edu.br/escritoriodedados/diagnostico-ofertas-if:${{ github.run_number }}"' 'diagnostico-ofertas-if_manifests/streamlit-app-configs/02-streamlit-app-deployment.yaml'

    - name: Push to Repo
      run: |
        # fix github permission - https://stackoverflow.com/questions/64374179/how-to-push-to-another-repository-in-github-actions
        # git config --unset-all http.https://github.com/.extraheader
      
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        ssh-add - <<< "${{secrets.DEPLOY_SSH_PRIVATE_KEY}}"

        # push to repository
        git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
        git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
        
        echo "Commitando tag da nova versão no repositório de manifestos..."
        cd diagnostico-ofertas-if_manifests
        ls -lha
        git add .
        git commit -m "Updated by GitHub Actions"
        git push -f